### ISSUE TITLE
Enhancement Request: Implementing Support for Additional ATP Solvers in ATPBatlab Package

### ISSUE THREAD

**Issue by costajr2019** [amaurigmartins/ATPBatlab#1]
Dear ATPBatlab Development Team,

I hope this message finds you well. I am reaching out to you today as beginner user of the ATPBatlab package available on the MathWorks File Exchange. First, I would like to extend my gratitude for your efforts in developing such a valuable tool that greatly facilitates the use of the ATP/EMTP for electrical system simulations.

I am writing to request an enhancement to the ATPBatlab package to broaden its compatibility and functionality. Specifically, I have identified a need for the package to support direct calls to additional ATP solvers, which are crucial for a variety of simulation scenarios. The solvers in question are: tpbig.exe, gigatp.exe, tpbigi64.exe, and tpgigi64.exe.

The inclusion of these solvers would significantly enhance ATPBatlab's usability for users who require these specific executables for their simulation tasks, due to their ability to handle larger and more complex models. This update would not only improve the flexibility of ATPBatlab but also ensure that it remains a highly relevant and valuable tool for the community.

I believe that many users, including myself, would greatly benefit from this update. It would enable us to perform a wider range of simulations directly within the MATLAB environment, thereby streamlining our workflow and increasing our productivity.

Could you please consider this request for inclusion in a future update of the ATPBatlab package? I, along with many in the community, would greatly appreciate this enhancement and are eager to see the continued evolution of this indispensable tool.

Thank you for considering my request. I look forward to your positive response and am happy to provide further details or clarification if needed.

Best regards.

**Comment by amaurigmartins** [comment]
Feature implemented (although poorly tested). Download the new mlapp file directly from the repository (do not use the release link). Test it and let me know in case of any issues.
